// src/sandbox/templates.ts
// Generated container artifacts for the sandbox. TS-string templates so they ship
// reliably in the npm package. The kernel-firewall logic (ipset + iptables
// deny-by-default) is ported from Isag (opensources/isag-main); node9 adds the
// node9-ai install, the in-box daemon, and the agent's hook wiring.
//
// The allowlist is NOT baked into the image — the host writes it to a mounted file
// (/etc/node9-sandbox/allowed-domains.txt) at run time, so the image stays
// content-stable (rebuild only on Dockerfile change, not on allowlist change).

import type { SandboxAgent, SandboxConfig } from './types';

const AGENT_NPM_PACKAGE: Record<SandboxAgent, string> = {
  claude: '@anthropic-ai/claude-code',
  codex: '@openai/codex',
};

/** The binary the agent user execs. */
const AGENT_BIN: Record<SandboxAgent, string> = {
  claude: 'claude',
  codex: 'codex',
};

export const RUN_AS_USER = 'agent';
export const ALLOWED_DOMAINS_PATH = '/etc/node9-sandbox/allowed-domains.txt';

/** node9-ai version to bake into the box — pin to the host's so they match. */
export function renderDockerfile(config: SandboxConfig, node9Version: string): string {
  const agentPkg = AGENT_NPM_PACKAGE[config.agent];
  return `# Auto-generated by node9 sandbox. Do not edit by hand.
FROM node:22-bookworm

ENV DEBIAN_FRONTEND=noninteractive

# Wall + base tooling (iptables/ipset/dig/gosu) — ported from Isag.
RUN apt-get update && apt-get install -y --no-install-recommends \\
        ca-certificates curl git gosu iproute2 ipset iptables dnsutils jq \\
    && rm -rf /var/lib/apt/lists/*

# The worker (agent CLI).
RUN npm install -g ${agentPkg}

# The guard (node9), pinned to the host version.
RUN npm install -g node9-ai@${node9Version}

# Non-root runtime user.
RUN useradd --create-home --uid 1000 --shell /bin/bash ${RUN_AS_USER}

# Wire the agent's node9 hooks into the runtime user's home (build-time, static).
RUN gosu ${RUN_AS_USER} node9 agents add ${config.agent} || true

RUN mkdir -p /workspace /etc/node9-sandbox \\
    && chown ${RUN_AS_USER}:${RUN_AS_USER} /workspace

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
`;
}

export const DOCKERIGNORE = `*
!Dockerfile
!entrypoint.sh
`;

/**
 * The entrypoint: seal the kernel firewall as root, then drop to the non-root agent
 * user which starts the node9 daemon and execs the agent. Firewall logic mirrors
 * Isag's resolver-union + deny-by-default approach.
 */
export function renderEntrypoint(config: SandboxConfig): string {
  const agentBin = AGENT_BIN[config.agent];
  return `#!/usr/bin/env bash
# Auto-generated by node9 sandbox. Seals the egress wall (root), then drops to the
# non-root agent which starts the node9 daemon + execs the agent.
set -Eeuo pipefail

DOMAINS_FILE="${ALLOWED_DOMAINS_PATH}"
RUN_AS_USER="${RUN_AS_USER}"

[[ -s "$DOMAINS_FILE" ]] || { echo "entrypoint: missing/empty $DOMAINS_FILE" >&2; exit 1; }

# Own the mounted node9 data dir so the agent user can write audit there.
mkdir -p "/home/$RUN_AS_USER/.node9"
chown -R "$RUN_AS_USER:$RUN_AS_USER" "/home/$RUN_AS_USER/.node9" || true

# ── Resolve the allowlist → ipset (union of every resolver, like Isag) ──────────
mapfile -t LOCAL_DNS < <(awk '/^nameserver / {print $2}' /etc/resolv.conf)
[[ \${#LOCAL_DNS[@]} -gt 0 ]] || { echo "entrypoint: no resolvers in /etc/resolv.conf" >&2; exit 1; }

ipset create node9_allowed hash:ip family inet -exist
ipset flush  node9_allowed

while IFS= read -r domain; do
    [[ -n "$domain" ]] || continue
    found=0
    # union the local resolver + each upstream so CDN/anycast IP rotation is covered
    for ip in $(getent ahostsv4 "$domain" 2>/dev/null | awk '{print $1}' | sort -u); do
        ipset add node9_allowed "$ip" -exist; found=1
    done
    for r in "\${LOCAL_DNS[@]}"; do
        for ip in $(dig +short +time=2 +tries=1 @"$r" A "$domain" 2>/dev/null | awk '/^[0-9.]+$/'); do
            ipset add node9_allowed "$ip" -exist; found=1
        done
    done
    [[ $found -eq 1 ]] || { echo "entrypoint: failed to resolve $domain" >&2; exit 1; }
    echo "entrypoint: allowed $domain"
done < "$DOMAINS_FILE"

# ── Seal iptables: deny-by-default except lo, established, DNS, the allowlist ────
echo "entrypoint: sealing firewall..."
iptables -F; iptables -X
iptables -P INPUT   DROP
iptables -P FORWARD DROP
iptables -P OUTPUT  DROP
iptables -A INPUT  -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT
iptables -A INPUT  -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
for r in "\${LOCAL_DNS[@]}"; do
    iptables -A OUTPUT -p udp -d "$r" --dport 53 -j ACCEPT
    iptables -A OUTPUT -p tcp -d "$r" --dport 53 -j ACCEPT
done
iptables -A OUTPUT -m set --match-set node9_allowed dst -j ACCEPT

# ── Drop to the agent: start the node9 daemon (as the user), then exec the agent ─
echo "entrypoint: starting node9 + ${agentBin} as $RUN_AS_USER"
exec gosu "$RUN_AS_USER" bash -lc '
  set -e
  node9 daemon --background >/dev/null 2>&1 || true
  cd /workspace
  exec ${agentBin} "$@"
' -- "$@"
`;
}
