/**
 * Generates the JavaScript extension file dropped into
 * `~/.pi/agent/extensions/node9.js` by setupPi.
 *
 * Why this lives in its own file (same reasoning as setup-opencode-shim.ts):
 *   - Keeps setup.ts from carrying ~150 lines of embedded JS source text.
 *   - Makes the shim contract testable in isolation.
 *
 * The generated shim wires four Pi extension hooks (contract verified
 * against /home/nadav/node9/opensources/pi-main):
 *
 *   • tool_call    — pre-execution block (return `{ block: true, reason }`,
 *                    NOT throw — pi's contract differs from opencode)
 *   • tool_result  — fire-and-forget audit log
 *   • input        — prompt DLP; block via `{ action: "handled" }`
 *   • user_bash    — !/!! prompt-escape side channel; block by returning
 *                    a synthetic failed BashResult (UserBashEventResult
 *                    has no `block` field — by design, since `pi.on("user_bash")`
 *                    is meant for execution-replacement, not gating).
 *
 * The shim spawnSyncs the node9 CLI via an embedded NODE9_ARGV array.
 * setupPi resolves that argv at install time so a stripped $PATH at pi
 * launch doesn't break interception.
 *
 * Tool-name normalization (design R5): pi tool names are lowercase
 * (`bash`/`read`/`edit`/`write`/...). The policy engine matches
 * PascalCase from Claude (`Bash`/`Read`/...). The shim normalizes before
 * spawning `node9 check` so existing rules engage with no policy edits.
 */

export interface PiShimInput {
  /**
   * The argv prefix used to invoke node9. Two production shapes:
   *
   *   • Global npm install — `["/usr/local/bin/node9"]`
   *   • Dev / npm-link    — `["/path/to/node", "/path/to/dist/cli.js"]`
   *
   * Resolved by setupPi at `node9 init` time via process.argv[1] /
   * process.execPath. The shim then invokes
   * `spawnSync(argv[0], [...argv.slice(1), "check"], ...)` which works
   * cross-platform without going through a shell.
   */
  node9Argv: string[];
  /**
   * Current node9 version. Embedded as a constant so subsequent inits
   * can detect mismatched shims and self-heal.
   */
  version: string;
}

export function renderPiShim(input: PiShimInput): string {
  const { node9Argv, version } = input;
  // Plain JavaScript — pi's loader uses jiti (packages/coding-agent/src/
  // core/extensions/loader.ts) which handles `module.exports` interop
  // across Node and the Bun-compiled binary path.
  return `// Auto-generated by \`node9 init\`. Do not edit — re-run init to upgrade.
// NODE9_SHIM_VERSION = "${version}"
//
// node9 protection shim for Pi (https://pi.dev). Wires four hooks
// against the agent's extension API and shells out to the node9 CLI
// for verdicts.
//
// Contract (verified against opensources/pi-main):
//   - tool_call  → return { block: true, reason } to block (NOT throw)
//   - tool_result → audit fire-and-forget
//   - input      → return { action: "handled" } to block, { action: "continue" } to allow
//   - user_bash  → return synthetic BashResult { output, exitCode: 1, ... } to block
//                  (UserBashEventResult has no block field by design)

const { spawnSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");

function debugLog(entry) {
  // Best-effort write to ~/.node9/hook-debug.log so audit-log failures
  // in the tool_result catch leave a breadcrumb. Pi has no equivalent
  // of node9's own hook-debug.log path, and silent swallow makes
  // misconfiguration invisible until block-rate dashboards catch on.
  // Wrapped in try because this hook NEVER throws — see catch comment.
  try {
    const logPath = path.join(os.homedir(), ".node9", "hook-debug.log");
    fs.mkdirSync(path.dirname(logPath), { recursive: true });
    fs.appendFileSync(logPath, JSON.stringify({
      ts: new Date().toISOString(),
      source: "pi-shim",
      ...entry,
    }) + "\\n");
  } catch (_) {
    // ignore — last-resort breadcrumb is best-effort
  }
}

// argv prefix for invoking the node9 CLI. argv[0] is the executable
// (either the npm-installed wrapper script or the node binary); the
// remaining entries (if any) are passed as the leading args before
// the subcommand name (e.g. ["/path/to/dist/cli.js"] for dev mode).
const NODE9_ARGV = ${JSON.stringify(node9Argv)};
const HOOK_TIMEOUT_MS = 30000;
const LOG_TIMEOUT_MS = 5000;

// Pi tool names → Claude tool names. Policy rules in ~/.node9/config.yaml
// match against Claude's PascalCase names (Bash/Read/Edit/Write/...).
// Without this mapping every DLP and project-jail rule silently no-ops
// for pi payloads (design R5).
const TOOL_NAME_MAP = {
  bash: "Bash",
  read: "Read",
  edit: "Edit",
  write: "Write",
  grep: "Grep",
  find: "Glob",
  ls: "LS",
};

function normalizeToolName(piName) {
  return TOOL_NAME_MAP[piName] || piName;
}

function parseReason(stdout) {
  // node9 check emits {decision, reason, message} JSON on stdout when
  // blocking. Fall back to a generic string if anything goes wrong.
  try {
    const v = JSON.parse(stdout || "");
    return v && (v.reason || v.message);
  } catch (e) {
    return null;
  }
}

function runCheck(payload, timeoutMs) {
  return spawnSync(NODE9_ARGV[0], [...NODE9_ARGV.slice(1), "check"], {
    input: JSON.stringify(payload),
    encoding: "utf-8",
    timeout: timeoutMs,
  });
}

module.exports = function (pi) {
  pi.on("tool_call", async (event, ctx) => {
    const payload = {
      hook_event_name: "PreToolUse",
      tool_name: normalizeToolName(event.toolName),
      tool_input: event.input,
      cwd: ctx.cwd,
      meta: { agent: "Pi" },
    };
    const r = runCheck(payload, HOOK_TIMEOUT_MS);
    if (r.status === 0) return undefined;
    const reason = parseReason(r.stdout) || "blocked by node9";
    return { block: true, reason: "[node9] " + reason };
  });

  pi.on("tool_result", async (event, ctx) => {
    // Audit + gap1 Mode A response-channel DLP: redact secrets in each text
    // content block before the model consumes the result. Pi's content is an
    // array of blocks; the host applies the handler's returned { content, isError }
    // back to the model (coding-agent agent-session.ts). Must NEVER throw or
    // return an error — the tool already completed.
    const auditPayload = {
      hook_event_name: "PostToolUse",
      tool_name: normalizeToolName(event.toolName),
      tool_input: event.input,
      cwd: ctx.cwd,
      meta: { agent: "Pi" },
    };
    const blocks = Array.isArray(event.content) ? event.content : [];
    const hasText = blocks.some(
      (b) => b && b.type === "text" && typeof b.text === "string" && b.text.length > 0
    );
    try {
      if (!hasText) {
        // No text to scan/redact — still record the tool call (audit-always).
        spawnSync(NODE9_ARGV[0], [...NODE9_ARGV.slice(1), "log"], {
          input: JSON.stringify(auditPayload),
          encoding: "utf-8",
          timeout: LOG_TIMEOUT_MS,
        });
        return undefined;
      }
      let mutated = false;
      const newContent = blocks.map((block) => {
        if (!block || block.type !== "text" || typeof block.text !== "string" || block.text.length === 0) {
          return block;
        }
        const r = spawnSync(NODE9_ARGV[0], [...NODE9_ARGV.slice(1), "log", "--redact-output"], {
          input: JSON.stringify({ ...auditPayload, tool_response: { output: block.text } }),
          encoding: "utf-8",
          timeout: LOG_TIMEOUT_MS,
        });
        if (r.status === 0 && r.stdout) {
          const resp = JSON.parse(r.stdout);
          if (resp && Array.isArray(resp.found) && resp.found.length > 0 && typeof resp.redacted === "string") {
            mutated = true;
            return { ...block, text: resp.redacted };
          }
        }
        return block;
      });
      if (mutated) return { content: newContent, isError: event.isError };
    } catch (e) {
      // Swallow + breadcrumb to ~/.node9/hook-debug.log (pi has no hook-debug
      // surface). A redaction/audit failure must not crash the agent.
      debugLog({
        event: "tool_result-spawn-failed",
        tool: auditPayload.tool_name,
        agent: "Pi",
        error: e && e.message ? e.message : String(e),
      });
    }
    return undefined;
  });

  pi.on("input", async (event, ctx) => {
    // Pre-prompt DLP. event.text is the user's typed/pasted prompt.
    // Block via { action: "handled" }; allow via { action: "continue" }.
    // We do NOT use { action: "transform" } in v1 — block-only mirrors
    // Claude/Codex/Opencode behavior. Redact-mode is a future option.
    const payload = {
      hook_event_name: "UserPromptSubmit",
      prompt: event.text,
      cwd: ctx.cwd,
      meta: { agent: "Pi" },
    };
    const r = runCheck(payload, HOOK_TIMEOUT_MS);
    if (r.status === 0) return { action: "continue" };
    const reason = parseReason(r.stdout) || "prompt blocked";
    if (ctx.hasUI) {
      ctx.ui.notify("[node9] " + reason, "error");
    }
    return { action: "handled" };
  });

  pi.on("user_bash", async (event, ctx) => {
    // The !/!! prompt-escape side channel (design R4). Synthesize a
    // Bash-shaped PreToolUse payload so the same dangerous-words / DLP
    // rules that gate tool_call(bash) also gate user_bash.
    //
    // UserBashEventResult has no { block } field — by design, since
    // pi.on("user_bash") was meant for execution-replacement. We block
    // by returning a synthetic BashResult that looks like the command
    // failed with our reason as the output (exitCode: 1).
    const payload = {
      hook_event_name: "PreToolUse",
      tool_name: "Bash",
      tool_input: { command: event.command },
      cwd: event.cwd,
      meta: { agent: "Pi" },
    };
    const r = runCheck(payload, HOOK_TIMEOUT_MS);
    if (r.status === 0) return undefined;
    const reason = parseReason(r.stdout) || "blocked by node9";
    if (ctx.hasUI) {
      ctx.ui.notify("[node9] " + reason, "error");
    }
    return {
      result: {
        output: "[node9] blocked: " + reason,
        exitCode: 1,
        cancelled: false,
        truncated: false,
      },
    };
  });
};
`;
}
